name: SkriptSecurity
version: ${project.version}
main: com.akon.skriptsecurity.SkriptSecurityMain
authors: [akon]
description: Skriptによるファイルへのアクセスや通信をブロックします
softdepend: [ProtocolLib]
loadbefore: [Skript]

permissions:
  skriptsecurity.admin:
    default: op